<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class BranchesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $branches = [
            [
                'code' => 'BR001',
                'name' => 'Cabang Jakarta Pusat',
                'address' => 'Jl. Merdeka No. 10',
                'city' => 'Jakarta Pusat',
                'province' => 'DKI Jakarta',
                'postal_code' => '10110',
                'phone' => '0211234567',
                'status' => 'active',
            ],
            [
                'code' => 'BR002',
                'name' => 'Cabang Bandung',
                'address' => 'Jl. Asia Afrika No. 22',
                'city' => 'Bandung',
                'province' => 'Jawa Barat',
                'postal_code' => '40111',
                'phone' => '0222345678',
                'status' => 'active',
            ],
            [
                'code' => 'BR003',
                'name' => 'Cabang Surabaya',
                'address' => 'Jl. Pemuda No. 45',
                'city' => 'Surabaya',
                'province' => 'Jawa Timur',
                'postal_code' => '60271',
                'phone' => '0313456789',
                'status' => 'active',
            ],
            [
                'code' => 'BR004',
                'name' => 'Cabang Yogyakarta',
                'address' => 'Jl. Malioboro No. 15',
                'city' => 'Yogyakarta',
                'province' => 'DI Yogyakarta',
                'postal_code' => '55122',
                'phone' => '0274123456',
                'status' => 'active',
            ],
            [
                'code' => 'BR005',
                'name' => 'Cabang Semarang',
                'address' => 'Jl. Pandanaran No. 30',
                'city' => 'Semarang',
                'province' => 'Jawa Tengah',
                'postal_code' => '50134',
                'phone' => '0246789012',
                'status' => 'active',
            ],
            [
                'code' => 'BR006',
                'name' => 'Cabang Medan',
                'address' => 'Jl. Gatot Subroto No. 12',
                'city' => 'Medan',
                'province' => 'Sumatera Utara',
                'postal_code' => '20111',
                'phone' => '0613456123',
                'status' => 'active',
            ],
            [
                'code' => 'BR007',
                'name' => 'Cabang Palembang',
                'address' => 'Jl. Sudirman No. 88',
                'city' => 'Palembang',
                'province' => 'Sumatera Selatan',
                'postal_code' => '30126',
                'phone' => '0711456789',
                'status' => 'active',
            ],
            [
                'code' => 'BR008',
                'name' => 'Cabang Pekanbaru',
                'address' => 'Jl. Jendral Sudirman No. 100',
                'city' => 'Pekanbaru',
                'province' => 'Riau',
                'postal_code' => '28112',
                'phone' => '0761789456',
                'status' => 'active',
            ],
            [
                'code' => 'BR009',
                'name' => 'Cabang Balikpapan',
                'address' => 'Jl. MT Haryono No. 5',
                'city' => 'Balikpapan',
                'province' => 'Kalimantan Timur',
                'postal_code' => '76112',
                'phone' => '0542789456',
                'status' => 'active',
            ],
            [
                'code' => 'BR010',
                'name' => 'Cabang Makassar',
                'address' => 'Jl. Ahmad Yani No. 9',
                'city' => 'Makassar',
                'province' => 'Sulawesi Selatan',
                'postal_code' => '90111',
                'phone' => '0411789456',
                'status' => 'active',
            ],
            [
                'code' => 'BR011',
                'name' => 'Cabang Denpasar',
                'address' => 'Jl. Teuku Umar No. 12',
                'city' => 'Denpasar',
                'province' => 'Bali',
                'postal_code' => '80113',
                'phone' => '0361789456',
                'status' => 'active',
            ],
            [
                'code' => 'BR012',
                'name' => 'Cabang Banjarmasin',
                'address' => 'Jl. Lambung Mangkurat No. 8',
                'city' => 'Banjarmasin',
                'province' => 'Kalimantan Selatan',
                'postal_code' => '70111',
                'phone' => '0511789456',
                'status' => 'active',
            ],
            [
                'code' => 'BR013',
                'name' => 'Cabang Manado',
                'address' => 'Jl. Sam Ratulangi No. 10',
                'city' => 'Manado',
                'province' => 'Sulawesi Utara',
                'postal_code' => '95111',
                'phone' => '0431789456',
                'status' => 'active',
            ],
            [
                'code' => 'BR014',
                'name' => 'Cabang Pontianak',
                'address' => 'Jl. Gajah Mada No. 11',
                'city' => 'Pontianak',
                'province' => 'Kalimantan Barat',
                'postal_code' => '78121',
                'phone' => '0561789456',
                'status' => 'active',
            ],
            [
                'code' => 'BR015',
                'name' => 'Cabang Bandar Lampung',
                'address' => 'Jl. Antasari No. 7',
                'city' => 'Bandar Lampung',
                'province' => 'Lampung',
                'postal_code' => '35122',
                'phone' => '0721789456',
                'status' => 'active',
            ],
            [
                'code' => 'BR016',
                'name' => 'Cabang Bogor',
                'address' => 'Jl. Pajajaran No. 20',
                'city' => 'Bogor',
                'province' => 'Jawa Barat',
                'postal_code' => '16128',
                'phone' => '0251789456',
                'status' => 'active',
            ],
            [
                'code' => 'BR017',
                'name' => 'Cabang Tangerang',
                'address' => 'Jl. Veteran No. 4',
                'city' => 'Tangerang',
                'province' => 'Banten',
                'postal_code' => '15111',
                'phone' => '0217894561',
                'status' => 'active',
            ],
            [
                'code' => 'BR018',
                'name' => 'Cabang Bekasi',
                'address' => 'Jl. Ahmad Yani No. 6',
                'city' => 'Bekasi',
                'province' => 'Jawa Barat',
                'postal_code' => '17111',
                'phone' => '0218894567',
                'status' => 'active',
            ],
            [
                'code' => 'BR019',
                'name' => 'Cabang Cirebon',
                'address' => 'Jl. Kartini No. 8',
                'city' => 'Cirebon',
                'province' => 'Jawa Barat',
                'postal_code' => '45112',
                'phone' => '0231789456',
                'status' => 'active',
            ],
            [
                'code' => 'BR020',
                'name' => 'Cabang Jember',
                'address' => 'Jl. Sultan Agung No. 5',
                'city' => 'Jember',
                'province' => 'Jawa Timur',
                'postal_code' => '68111',
                'phone' => '0331789456',
                'status' => 'active',
            ],
        ];

        DB::table('branches')->insert($branches);
    }
}
